<div class="plain-box"><h2>What's New in Release 31</h2>
<div class="info-box embedded-box float-right"><h3>Did you know...?</h3><p><a href="http://ensemblgenomes.org/info/data/rfam_alignment"><img alt="Read more" src="/img/9796ea51.png" style="float:right; height:50px; margin:1px 5px; width:50px" title="" /></a></p>

<p>We have performed <a href="http://ensemblgenomes.org/info/data/rfam_alignment">ncRNA alignments</a><!--nbsp--> <!--nbsp-->across<!--nbsp--> <!--nbsp-->all plant species?</p></div>
<ul><li>New data
	<ul><li>New <a href="http://plants.ensembl.org/Oryza_sativa/Info/Annotation#variation">variation data for rice</a>.</li>
		<li>New <a href="http://plantreactome.gramene.org/">Plant Reactome</a> cross references added to all species.</li>
		<li>New <a href="http://ensemblgenomes.org/info/data/rfam_alignment">ncRNA alignment</a> across all plant species.</li>
		<li>New <a href="http://ensemblgenomes.org/info/access/public-track-hubs">track hubs</a> for more than 900 public RNA-Seq studies, totaling more than 16,000 tracks across 35 plant species.</li></ul>
	</li>
	<li>Updated data
	<ul><li>Updated BioMarts.</li>
		<li>Updated protein domain information based on latest InterProScan.</li></ul>
	</li></ul>
</div>